# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OptionsGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_group_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=50)),
                ('vendor_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description_short', models.CharField(max_length=600)),
                ('product_description_long', models.TextField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('product_weight', models.DecimalField(decimal_places=3, max_digits=3)),
                ('product_stock', models.PositiveSmallIntegerField()),
                ('products_ordered', models.PositiveSmallIntegerField()),
                ('product_available', models.BooleanField(default=True)),
                ('discount_available', models.BooleanField()),
                ('is_bestseller', models.BooleanField()),
                ('product_image', models.URLField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.Brand')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=20)),
                ('made_in', models.CharField(max_length=50)),
                ('fabrics', models.CharField(max_length=150)),
                ('option_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.OptionsGroups')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.Product')),
            ],
        ),
    ]
