# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_style_edits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='options',
            options={'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='optionsgroups',
            options={'verbose_name_plural': 'Options Groups'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productoptions',
            options={'verbose_name_plural': 'Product Options'},
        ),
    ]
