# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_new_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Unisex')], max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='product_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
