# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import shop_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0011_fields_edits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='large',
            field=models.ImageField(blank=True, max_length=300, upload_to=shop_app.models.upload_large_img),
        ),
        migrations.AlterField(
            model_name='image',
            name='medium',
            field=models.ImageField(blank=True, max_length=300, upload_to=shop_app.models.upload_medium_img),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=300, upload_to=shop_app.models.upload_thubm_img),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('Uni', 'Unisex')], max_length=3),
        ),
    ]
