# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0012_fields_edits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
    ]
