# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0017_user_auth3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'user info', 'verbose_name_plural': 'users info'},
        ),
    ]
