# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import shop_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0018_auth3'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='preview',
            field=models.ImageField(blank=True, max_length=300, upload_to=shop_app.models.upload_preview_img),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
